# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 987443f5f7edec549a480e7c2190f86ec3befee1143902ec359029008ffd1e86037f32c5945ea3a25723f9bb2d6324c8a85b26963354deec771b433adbc6fcc0

test:
  secret_key_base: c3717596543c619b7e256fad50315da963627b2f2fb2938e031494069b2236d0f3b044ec0da939ee5c5d220dcd50d701dc5368e293751647a4a91a6b2776cd36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
